//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllichsuthaydoiyeucau
    {
        public string ma_lich_su { get; set; }
        public string ma_nhan_vien { get; set; }
        public string ma_yeu_cau { get; set; }
        public string trang_thai_xu_ly { get; set; }
        public string noi_dung { get; set; }
        public string loai_thay_doi { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        public virtual tblnguoidung tblnguoidung { get; set; }
        public virtual tblyeucauhotrokythuat tblyeucauhotrokythuat { get; set; }
    }
}
