//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphongban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblphongban()
        {
            this.tblyeucauhotrokythuats = new HashSet<tblyeucauhotrokythuat>();
            this.tblnguoidungs = new HashSet<tblnguoidung>();
            this.tblquyens = new HashSet<tblquyen>();
        }
    
        public string ma_phong_ban { get; set; }
        public string ten_phong_ban { get; set; }
        public Nullable<bool> trang_thai { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblyeucauhotrokythuat> tblyeucauhotrokythuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnguoidung> tblnguoidungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblquyen> tblquyens { get; set; }		
	}
}
