//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblquyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblquyen()
        {
            this.tblphongbans = new HashSet<tblphongban>();
        }
    
        public string ma_quyen { get; set; }
        public string ma_chuc_nang { get; set; }
        public string ten_quyen { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> cap_nhat { get; set; }
    
        public virtual tblchucnang tblchucnang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblphongban> tblphongbans { get; set; }
    }
}
