//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblyeucauhotrokythuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblyeucauhotrokythuat()
        {
            this.tbllichsuthaydoiyeucaus = new HashSet<tbllichsuthaydoiyeucau>();
        }
    
        public string ma_yeu_cau { get; set; }
        public string ten_yeu_cau { get; set; }
        public string noi_dung_yeu_cau { get; set; }
        public Nullable<System.DateTime> ngay_tiep_nhan { get; set; }
        public Nullable<System.DateTime> ngay_xu_ly { get; set; }
        public string trang_thai_xu_ly { get; set; }
        public string ma_khach_hang { get; set; }
        public string ma_phong_ban { get; set; }
    
        public virtual tblkhachhang tblkhachhang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbllichsuthaydoiyeucau> tbllichsuthaydoiyeucaus { get; set; }
        public virtual tblphongban tblphongban { get; set; }
    }
}
